Finished day 1
gusttavoaguiarr/advent-of-code-2015 pull request #2
Opened 2017-07-05 21:31 UTC by gusttavoaguiarr

2017-07-05 21:46 UTC, ricardoruwer commented
A mensagem de commit poderia ser alguma coisa como:
`Allow Santa to go up and downstairs 🎅`

2017-07-05 21:47 UTC, ricardoruwer commented on day1/floor.py
> +class FloorTest(unittest.TestCase):
Esses testes deveriam estar em outro arquivo?

2017-07-05 21:50 UTC, ricardoruwer commented on day1/floor.py
> +		self.assertEqual(self.floor.floor_position('(((('), 4)
Acho que vc não precisa fazer esses 3 testes onde no primeiro ele sobe 1 andar, no segundo ele sobre 2 andares e no terceiro ele sobe 4 andares.

Pra mim parece que os 3 testes estão testando exatamente a mesma coisa, sem diferença nenhuma entre eles.
Ou seja, vc poderia remover 2 destes testes acima.

2017-07-05 21:50 UTC, ricardoruwer commented on day1/floor.py
> +		self.assertEqual(self.floor.floor_position('))))'), -4)
Aqui o mesmo que comentei sobre o teste de subir os andares. Acho que pode deixar só 1 deles.

2017-07-05 21:51 UTC, ricardoruwer commented on day1/floor.py
> +		self.assertEqual(self.floor.floor_position(')())())'), -3)
E aqui também a mesma coisa.
No fim, vc vai ter apenas 3 testes na sua suite:
1. Onde o Santa só sobe
2. Onde o Santa só desce
3. Onde o Santa sobe e desce e desce e sobe e desce e etc.

2017-07-05 21:54 UTC, ricardoruwer commented on day1/floor.py
> +	def __init__(self):
Deixa eu perguntar uma coisa, aonde vc está usando o valor do `input.txt`? Como vc fez para saber qual a resposta correta?

2017-07-05 21:56 UTC, ricardoruwer commented on day1/floor.py
> +		self.floor = Floor()
Não é mais fácil usar:
`self.assertEqual(Floor().floor_position('('), 1)`
do que fazer esse Setup aí? 🤔

2017-07-05 21:58 UTC, ricardoruwer commented on day1/floor.py
> +	def floor_position(self, value):
Uma outra forma de saber qual é o andar que o Santa está é assim:

```
vezes_que_subiu = (conta quantos caracteres tem de `(`)
vezes_que_desceu = (conta quantos caracteres tem de `)`)

return vezes_que_subiu - vezes_que_desceu
```

Correto? 🤔 
Acho que talvez a performance seja melhor

2017-07-05 22:10 UTC, gusttavoaguiarr commented on day1/floor.py
> +class FloorTest(unittest.TestCase):
Sim, vou fazer essa mudança

2017-07-05 22:13 UTC, gusttavoaguiarr commented on day1/floor.py
> +		self.assertEqual(self.floor.floor_position('(((('), 4)
Sim concordo mas como eu estava praticando TDD fiz passo a passo e ai acabei mantendo esses testes.

2017-07-05 22:25 UTC, lohanbodevan requested changes

2017-07-05 22:25 UTC, lohanbodevan commented on day1/floor.py
> +
Devem ter duas linhas entre os imports e a classe.
https://www.python.org/dev/peps/pep-0008/#blank-lines

2017-07-05 22:25 UTC, lohanbodevan commented on day1/floor.py
> +		self.floor = Floor()
Este `setUp` vai criar uma instancia de `Floor` antes de cada teste. Essa é a intenção?

2017-07-05 22:25 UTC, lohanbodevan commented on day1/floor.py
> +
Muitas linhas em branco antes da classe

2017-07-05 22:25 UTC, lohanbodevan commented on day1/floor.py
> +
Deve-ser ter apenas uma linha em branco entre funções. 
https://www.python.org/dev/peps/pep-0008/#blank-lines

2017-07-05 22:28 UTC, lohanbodevan commented
Seria interessantes implementar o um lint para evitar inconsistências de code-style.
https://pypi.python.org/pypi/flake8

2017-07-06 14:27 UTC, ricardoruwer commented
Também faltou uma mensagem nesse Pull Request!
Vc pode separar a mensagem do PR por tópicos, como por exemplo:


## O que esse PR faz?

Descrição.

## TODOs

- [ ] Docs

## Screenshots

Screenshots, GIFs, `curl` examples, sample code, etc.

## Dúvidas

- Ficou bonito?
- Como faz XPTO?

2017-07-06 14:31 UTC, ricardoruwer commented
Vi que sua mensagem de commit vc colocou "Terminado o dia 1".

O recomendado é vc escrever no modo imperativo, como se estivesse comandando alguém. Escreva: "adiciona", "remove", "atualiza" ao invés de "adicionado", "removido", "atualizado".

2017-07-06 20:41 UTC, gusttavoaguiarr commented on day1/floor.py
> +		self.floor = Floor()
@ricardoruwer o setUp ele cria uma instancia antes de cada teste, como o @lohanbodevan disse ai em baixo, mas vou fazer essa troca e instanciar antes faz mas sentido eu coloco "Floor().floor_position.."

2017-07-06 20:42 UTC, gusttavoaguiarr commented on day1/floor.py
> +	def floor_position(self, value):
Sim faz mas sentido

2017-07-06 21:55 UTC, ricardoruwer commented
Sua mensagem de commit foi:
Moved the testes to the file test, removed unnecessary tests and updated code

Aqui encontramos alguns problemas:
1. Essa mensagem tem 77 caracteres e se não me engano o limite é 70.
2. Vc está fazendo 3 coisas:
- Moved the testes to the file test
- Removed unnecessary tests
- Updated code
Então cada uma delas poderia ser 1 commit separado, ou seja, vc trocaria esse seu único commit por 3 commits.
3. Nas mensagens de commit a gente não usa `Moved`, mas sim `Move`. Não usamos `Removed`, mas sim `Remove`. Não usamos `Updated`, mas sim `Update`.
4. A sua mensagem de `Updated code` está muito vaga, seria melhor ser mais específico o que vc está atualizando 🤔

2017-07-06 22:19 UTC, ricardoruwer commented
Sua mensagem de commit foi:
Moved the testes to the file test, removed unnecessary tests and updated code

Aqui encontramos alguns problemas:
1. Essa mensagem tem 77 caracteres e se não me engano o limite é 70.
2. Vc está fazendo 3 coisas:
- Moved the testes to the file test
- Removed unnecessary tests
- Updated code
Então cada uma delas poderia ser 1 commit separado, ou seja, vc trocaria esse seu único commit por 3 commits.
3. Nas mensagens de commit a gente não usa `Moved`, mas sim `Move`. Não usamos `Removed`, mas sim `Remove`. Não usamos `Updated`, mas sim `Update`.
4. A sua mensagem de `Updated code` está muito vaga, seria melhor ser mais específico o que vc está atualizando 🤔 

Isso é bom de fazer até pra vc já acostumar a fazer do jeito certo :)

E mais outra coisa a se pensar:
Tá tudo bem vc ter vários commits aqui, agora, para nós, durante o code review, analisarmos o andamento da sua US. 
Mas, antes de vc aceitar esse Pull Request e mergear ele na master, é bom vc dar um `squash` de todos esses commits em 1 commit só, talvez chamado de `Allow Santa to go up and downstairs 🎅`!

2017-07-07 01:15 UTC, ricardoruwer requested changes

2017-07-07 01:15 UTC, ricardoruwer commented on day1/floor.py
> +		while count < len(value):
Não existe uma função no Python que conta quantos caracteres `(` tem dentro de uma string? Para podermos eliminar esse `while`.

2017-07-07 01:15 UTC, ricardoruwer commented on day1/floor.py
> +		time_down = 0
Essa identação acima está correta? 🤔

2017-07-07 01:15 UTC, ricardoruwer commented on day1/floor.py
> +		while count < len(value):
Daí vc poderia simplificar em algo como:

```python
up = value.characters.count('(')
down = value.characters.count(')')
return up - down
```

2017-07-07 01:15 UTC, ricardoruwer commented on day1/tests.py
> +		self.assertEqual(Floor().floor_position_input('input.txt'), 138)
Estou em dúvida quanto a esse teste. Porque se algum dia eu quiser fazer o meu Advent Of Code em Python e quiser trapacear e usar o seu código para chegar ao resultado, eu vou lá e altero o input.txt para chegar ao resultado, mas o teste vai quebrar 😞 

Acho que o teste até é válido, para validar que ele está lendo um arquivo externo... Mas acho que não seria correto o mesmo arquivo que é usado para chegar no resultado... Fui claro? Faz sentido? 🤔 
Talvez seria mais válido se vc tivesse tipo um outro arquivo tipo `test/fixtures/input.txt` com algum outro valor qualquer e vc usasse ele para realizar seus testes.

2017-07-07 01:20 UTC, ricardoruwer commented on day1/tests.py
> +		self.assertEqual(Floor().floor_position_input('input.txt'), 138)
O que vc acha @lohanbodevan ? Faz sentido? 🤔

2017-07-07 01:21 UTC, ricardoruwer commented on day1/tests.py
> +import unittest
Será que esse arquivo de testes não faria mais sentido em algum caminho como: `day1/tests/floor_test.py`? 🤔

2017-07-07 01:32 UTC, ricardoruwer commented on day1/floor.py
> +			if value[count] == '(':
Uma outra coisa para melhorar seu código é pensar:
OK, mas o que diabos significa esse `'('`? O que são esses parênteses?
Daí vc cria uma variável de instância para dizer o que são.

Não sei como se faz isso em Python, mas vc define algo como:
```python
MOVE_UP = '('
MOVE_DOWN = ')'
```

2017-07-07 01:34 UTC, ricardoruwer commented on day1/floor.py
> +			if value[count] == '(':
Daí seguindo a dica que dei logo ali em cima, seu código ficaria algo do tipo:

```python
up = value.characters.count(MOVE_UP)
down = value.characters.count(MOVE_DOWN)
return up - down
```

Fica mais intuitivo, não acha? 🤔

2017-07-07 02:00 UTC, lohanbodevan commented on day1/tests.py
> +		self.assertEqual(Floor().floor_position_input('input.txt'), 138)
Sim, o ideal é usar um 'fixture'. E em Python o mais utilizado é essa estrutura que você mandou mesmo Ricardo.

2017-07-11 19:27 UTC, gusttavoaguiarr commented
## What are you doing

The goal is to write a code that on receiving the input '(' Santa goes up one floor and receives an input ')' down one floor. So I wrote a method to find out what the current floor is.

## TODOs

- [ ]  End the exercise of PART 2

## Doubts

- I was unsure if the tests I wrote are really correct or if it can be better

2017-07-11 19:28 UTC, gustavodfaguiar reviewed
## What are you doing

The goal is to write a code that on receiving the input '(' Santa goes up one floor and receives an input ')' down one floor. So I wrote a method to find out what the current floor is.

## TODOs

- [ ]  End the exercise of PART 2

## Doubts

- I was unsure if the tests I wrote are really correct or if it can be better

2017-07-11 19:28 UTC, gusttavoaguiarr commented on day1/floor.py
> +		while count < len(value):
Tem sim, vou realizar essa modificação

2017-07-11 19:28 UTC, gusttavoaguiarr commented on day1/tests.py
> +import unittest
Faz sentido mas como não tem muitos testes para dividir por exemplo: Teste da view, teste do model, etc..,  é apenas um teste para um função então não vejo necessidade

2017-07-11 20:23 UTC, ricardoruwer commented on day1/tests.py
> +import unittest
Ou mudar o nome do arquivo para `floor_test.py` pelo menos 😆

2017-07-11 20:49 UTC, gusttavoaguiarr commented on day1/floor.py
> +			if value[count] == '(':
Fica sim, não tinha pensando desta maneira, vou aplicar essas mudanças

2017-07-12 01:41 UTC, ricardoruwer commented on day1/floor.py
> +        return self.calc_position(value)
Aqui não é mais fácil só usar:

```python
return self.calc_position(floors)
```

🤔

2017-07-12 01:43 UTC, ricardoruwer commented on day1/floor_test.py
> +        self.assertEqual(Floor().floor_position_input('input.txt'), 138)
Acho que com esse teste vc acaba ficando muito amarrado...

A intenção acho que seria que ao alterarmos o arquivo `input.txt` o código ainda estivesse todo OK. E esse teste não vai deixar isso acontecer...

O teste até é válido, pq garante também que um arquivo de texto está sendo lido, mas talvez devêssemos mover esse arquivo de teste para dentro de uma pasta `test/fixtures/input.txt`. E esse teste para dentro `test/floor_test.py` ou `test/unit/floor_test.py`. Faz sentido?

Ou talvez apenas removê-lo... 🤔

2017-07-12 01:45 UTC, ricardoruwer commented on day1/floor_test.py
> +
É comum ter 2 espaços aqui?

2017-07-12 01:50 UTC, ricardoruwer commented
Uma coisa que senti falta também foi:

- Criar um arquivo, sei lá, tipo `index.py` com coisas tipo assim:

```python
require 'floor.py'

santa_current_floor = Floor().floor_position_input('input.txt')

puts 'To what floor do the instructions take Santa?'
puts santa_current_floor
```

Então quando vc rodar no terminal um comando do tipo:

```
python index.py
```

Ele vai escrever na sua tela:

```
To what floor do the instructions take Santa?
138
```

Faz sentido? 🤔

2017-07-12 16:07 UTC, gusttavoaguiarr commented on day1/floor_test.py
> +        self.assertEqual(Floor().floor_position_input('input.txt'), 138)
Faz sentido, vou realizar essas modificações

2017-07-12 16:29 UTC, gusttavoaguiarr commented on day1/floor_test.py
> +
Sim

2017-07-12 17:36 UTC, ricardoruwer commented on day1/floor_test.py
> +        self.assertEqual(Floor().floor_position('('), 1)
Se vc chamar
```python
self.assertEqual(Floor().calc_position('('), 1)
```
Também funciona?

Se sim, vc pode eliminar o método `floor_position` da sua classe, pq ele não está fazendo nada 🤔

2017-07-13 00:32 UTC, gusttavoaguiarr commented on day1/floor_test.py
> +        self.assertEqual(Floor().floor_position('('), 1)
Também funciona, já vou realizar essa troca

2017-07-13 01:22 UTC, ricardoruwer commented on setup.py
> +      packages=['day1'])
**EU** acho essa indentação meio feia... Prefiro algo assim:

```python
setup(
    name='day1',
    version='0.1',
    description='Production Code',
    packages=['day1']
)
```

E essa `description` pode ser algo mais voltado ao propósito do app? Tipo "Day 1 of Advent of Code 2015" ou "Help Santa to deliver presents in a large apartment building". Faz sentido? 🤔

2017-07-13 01:25 UTC, ricardoruwer commented on day1/test/floor_test.py
> +            'test/fixtures/input.txt'), 138)
E nessa indentação eu deixaria tudo em 1 linha só, porque não passa dos 80 caracteres, mas se precisasse indentar, eu faria algo assim:

```python
self.assertEqual(
    Floor().floor_position_input('test/fixtures/input.txt'), 138
)
```

ou senão

```python
self.assertEqual(
    Floor().floor_position_input('test/fixtures/input.txt'), 
    138
)
```

💅

2017-07-13 01:38 UTC, ricardoruwer commented on day1/app.py
> +santa_current_floor = Floor().floor_position_input('test/fixtures/input.txt')
Eu, na realidade, ainda faria algo mais diferente 😸 
Já cansou de tantos comentários meus aqui? 😹😹

Seria assim, ó:

Aqui nesse arquivo `app.py`:
```python
input = open('test/fixtures/input.txt').read()
santa_current_floor = Floor.new(input).santa_current_floor

print('To what floor do the instructions take Santa?')
print(santa_current_floor)
```

Daí no arquivo `floor.py` deixaria tipo assim:
```python
MOVE_UP = '('
MOVE_DOWN = ')'

def constructor(input)
    self.input = input

def santa_current_floor
    up = self.input.count(MOVE_UP)
    down = self.input.count(MOVE_DOWN)
    return up - down
```

Porque assim a gente consegue remover a responsabilidade da classe `Floor` de ler um arquivo, e deixamos ela apenas com a responsabilidade de calcular o andar.

Acha que faz sentido, @gusttavoaguiarr e @lohanbodevan ?

2017-07-13 02:44 UTC, lohanbodevan commented on day1/app.py
> +santa_current_floor = Floor().floor_position_input('test/fixtures/input.txt')
Concordo!

2017-07-17 21:18 UTC, gusttavoaguiarr commented on setup.py
> +      packages=['day1'])
Vou ter que fazer a troca desse código a maneira que implementei não está correta

2017-07-17 21:32 UTC, gusttavoaguiarr commented on day1/app.py
> +santa_current_floor = Floor().floor_position_input('test/fixtures/input.txt')
Sim faz sentido, estou fazendo as modificações

2017-07-26 21:44 UTC, ricardoruwer requested changes

2017-07-26 21:44 UTC, ricardoruwer commented on day1/app.py
> +input = open('test/fixtures/input.txt').read()
Aqui vc deveria carregar um arquivo que não seja uma fixture... Porque isso aqui não é um teste :P

2017-07-26 21:44 UTC, ricardoruwer commented on day1/app.py
> +print(santa_current())
Credo, precisa mesmo desse `()`? Talvez então seja melhor colocá-lo lá em cima, no:

```python
santa_current = Floor(input).santa_current_floor()
```

E tirar as `()` desse aqui.

Faz sentido?

2017-07-26 21:44 UTC, ricardoruwer commented on day1/floor.py
> +        return int(moves_up - moves_down)
Esse `int()` é pra transformar o resultado em um número inteiro? Mas o resultado já não vai ser um número inteiro mesmo sem ele?

2017-07-26 21:53 UTC, gusttavoaguiarr commented on day1/app.py
> +input = open('test/fixtures/input.txt').read()
Saquei

2017-07-26 21:53 UTC, gusttavoaguiarr commented on day1/app.py
> +print(santa_current())
Faz sentido sim, vou dar uma olhada nisso

2017-07-27 14:33 UTC, ricardoruwer commented on day1/test/floor_test.py
> +
Vc tem o arquivo `day1/test/fixtures/input.txt` mas nenhum teste que usa ele 🤔 
Ou adiciona esse teste, ou remove o arquivo 😆

2017-07-28 11:33 UTC, lohanbodevan commented on day1/app.py
> +santa_current = Floor(input).santa_current_floor()
Essa váriavel `santa_current` está sendo criada apenas para o `print` logo abaixo.
Isto não é impeditivo e nem precisa mudar, só gostaria de aproveitar a oportunidade para levantar a questão: Será que você precisa dela? Você poderia fazer o `print` no resultado da função diretamente. Exemplo:
```
print(Floor(input).santa_current_floor())
```
Este tipo de questionamento vai surgir quando você começar a se familiarizar com programação funcional.

2017-07-28 11:40 UTC, lohanbodevan commented on day1/floor.py
> +    def santa_current_floor(self):
[NON-BLOCKING] Esse método retorna um estado correto? Ou seja, ele executa um algoritmo e retorna uma propriedade, ele não faz verificações, não faz nenhum operação que lança exception ou coisa do tipo.
Sendo assim este método é um ótimo candidato a virar uma `property`, um conceito bem bacana do Python.

Acredito que você já saiba mas vale lembrar `property` são métodos disfarçados de atributos de instancia de uma classe.
Seu método ficaria assim:

```
@property
def santa_current_floor(self):
    moves_up = self.input.count(self.MOVE_UP)
    moves_down = self.input.count(self.MOVE_DOWN)
    return moves_up - moves_down
```

Desta forma você invocaria esse método como se ele fosse um atributo da sua classe:
```
Floor(input).santa_current_floor
```

Se você reparar, agora faz ainda mais sentido utilizar essa chamada diretamente no `print`, que falei no comentário anterior.

2017-07-31 13:40 UTC, gusttavoaguiarr commented on day1/floor.py
> +    def santa_current_floor(self):
@lohanbodevan no caso seria um metódo estático o "@property"?

2017-08-08 22:28 UTC, ricardoruwer requested changes
🙌

2017-08-08 22:28 UTC, ricardoruwer commented on day1/floor.py
> +    def __init__(self, input, basement):
Acho que vc não precisa definir o `basement` no método construtor, porque ele sempre será `-1`, não?

Então acho que dá pra você jogar isso em uma constante ali em cima:

```python
BASEMENT = '-1'
```

2017-08-08 22:28 UTC, ricardoruwer commented on day1/floor.py
> +            if floor == -1:
Seguindo aquela ideia que dei de colocar o `BASEMENT` em uma constante, você poderia alterar aqui também para:

```python
if floor == BASEMENT:
```

Bem mais legível :)

2017-08-08 22:28 UTC, ricardoruwer commented on day1/floor.py
> +        for move in self.input:
Você consegue pegar o `index` aqui desse `for`?

Talvez algo como:

```python
for index, move in self.input:
```

🤔 

Porque se conseguir, vc não precisa definir a variável `first_enter_basement` e nem dar um `+= 1` nela, igual logo ali em baixo.

Daí poderia ficar algo do tipo, ali em baixo:

```python
if floor == BASEMENT:
    return index + 1
```

Talvez também seja mais performático. :)

2017-08-08 22:28 UTC, ricardoruwer commented on day1/app.py
> +print(Floor(input, -1).santa_current_floor)
Aqui você tá usando o mesmo método `santa_current_floor` para 2 coisas diferentes, então ele tá ficando estranho. 🤔 
Para a primeira pergunta, ele faz sentido, mas para a segunda pergunta, não.
A pergunta é "Quando que o Papai Noel entrou no porão?" e vc responde chamando uma função com o nome de "andar_atual"? 🤔 Compreende que não faz sentido?

Eu faria algo tipo assim:

```python
print('To what floor do the instructions take Santa?')
print(Floor(input).santa_current_floor)
print('What is the position of the character that causes Santa to first enter the basement?')
print(Floor(input).santa_first_time_at_basement)
```

Até diria outra coisa: percebe que as perguntas são sempre para saber coisas do Papai Noel?
Não faria mais sentido essa classe, ao invés de se chamar `Floor`, ela se chamar `Santa`?

Daí ficaria:

```python
Santa(input).current_floor
Santa(input).first_time_at_basement
```

2017-08-08 22:28 UTC, ricardoruwer commented on day1/floor.py
> +    def santa_current_floor(self):
Como disse em outro comentário: vc não precisa usar 1 método só para responder as 2 perguntas.

Use o método `current_floor` para responder uma pergunta e o método `first_enter_basement` para responder a outra.

2017-08-09 16:32 UTC, ricardoruwer commented on setup.py
> +      packages=['day1', 'day2'])
Por enquanto só o `day1` né? 😸

2017-08-09 16:34 UTC, ricardoruwer commented on setup.py
> +      description='Advent of code',
Acho que tem a versão `2015` e a `2016`. A que vc está fazendo é a de `2015`, talvez valha colocar aí na descrição.

2017-08-11 00:59 UTC, gusttavoaguiarr commented on day1/app.py
> +print(Floor(input, -1).santa_current_floor)
SIm faz todo sentido, não tinha reparado nisso vou realizar as modificações @ricardoruwer

2017-08-11 01:00 UTC, gusttavoaguiarr commented on day1/floor.py
> +    def __init__(self, input, basement):
Sim, vou realizar essa mudança também

2017-08-11 02:54 UTC, ricardoruwer commented on README.md
> +- [ ] Day 10
Só uma observação: quando for dar um squash, seria interessante esse arquivo aqui ir em um commit separado, porque ele tá em outro contexto.

2017-08-11 02:58 UTC, ricardoruwer commented
Achei que ficou topster! 👏 🙌 ✨ 

Agora é hora de dar uma praticada no GIT e dar um squash nesse monte de commit.

Acho que você poderia separar em 2 commits:
- Um com o README.md
- Um com todo o resto

O que acha? Faz sentido? Se precisar de ajuda pra fazer, dá um grito :D

2017-08-11 02:58 UTC, gusttavoaguiarr commented on README.md
> +- [ ] Day 10
Como faço isso?

2017-08-12 16:35 UTC, merged

2017-08-12 19:51 UTC, ricardoruwer commented
Mergeou sem aprovação e sem arrumar a árvore de commits 👎